// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: protobuf/v1/watchlist.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WatchlistService_CreateWatchlistItem_FullMethodName = "/wealthjourney.watchlist.v1.WatchlistService/CreateWatchlistItem"
	WatchlistService_ListWatchlist_FullMethodName       = "/wealthjourney.watchlist.v1.WatchlistService/ListWatchlist"
	WatchlistService_UpdateWatchlistItem_FullMethodName = "/wealthjourney.watchlist.v1.WatchlistService/UpdateWatchlistItem"
	WatchlistService_DeleteWatchlistItem_FullMethodName = "/wealthjourney.watchlist.v1.WatchlistService/DeleteWatchlistItem"
	WatchlistService_ReorderWatchlist_FullMethodName    = "/wealthjourney.watchlist.v1.WatchlistService/ReorderWatchlist"
	WatchlistService_CheckWatchlistItem_FullMethodName  = "/wealthjourney.watchlist.v1.WatchlistService/CheckWatchlistItem"
)

// WatchlistServiceClient is the client API for WatchlistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchlistServiceClient interface {
	CreateWatchlistItem(ctx context.Context, in *CreateWatchlistItemRequest, opts ...grpc.CallOption) (*CreateWatchlistItemResponse, error)
	ListWatchlist(ctx context.Context, in *ListWatchlistRequest, opts ...grpc.CallOption) (*ListWatchlistResponse, error)
	UpdateWatchlistItem(ctx context.Context, in *UpdateWatchlistItemRequest, opts ...grpc.CallOption) (*UpdateWatchlistItemResponse, error)
	DeleteWatchlistItem(ctx context.Context, in *DeleteWatchlistItemRequest, opts ...grpc.CallOption) (*DeleteWatchlistItemResponse, error)
	ReorderWatchlist(ctx context.Context, in *ReorderWatchlistRequest, opts ...grpc.CallOption) (*ReorderWatchlistResponse, error)
	CheckWatchlistItem(ctx context.Context, in *CheckWatchlistItemRequest, opts ...grpc.CallOption) (*CheckWatchlistItemResponse, error)
}

type watchlistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchlistServiceClient(cc grpc.ClientConnInterface) WatchlistServiceClient {
	return &watchlistServiceClient{cc}
}

func (c *watchlistServiceClient) CreateWatchlistItem(ctx context.Context, in *CreateWatchlistItemRequest, opts ...grpc.CallOption) (*CreateWatchlistItemResponse, error) {
	out := new(CreateWatchlistItemResponse)
	err := c.cc.Invoke(ctx, WatchlistService_CreateWatchlistItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) ListWatchlist(ctx context.Context, in *ListWatchlistRequest, opts ...grpc.CallOption) (*ListWatchlistResponse, error) {
	out := new(ListWatchlistResponse)
	err := c.cc.Invoke(ctx, WatchlistService_ListWatchlist_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) UpdateWatchlistItem(ctx context.Context, in *UpdateWatchlistItemRequest, opts ...grpc.CallOption) (*UpdateWatchlistItemResponse, error) {
	out := new(UpdateWatchlistItemResponse)
	err := c.cc.Invoke(ctx, WatchlistService_UpdateWatchlistItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) DeleteWatchlistItem(ctx context.Context, in *DeleteWatchlistItemRequest, opts ...grpc.CallOption) (*DeleteWatchlistItemResponse, error) {
	out := new(DeleteWatchlistItemResponse)
	err := c.cc.Invoke(ctx, WatchlistService_DeleteWatchlistItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) ReorderWatchlist(ctx context.Context, in *ReorderWatchlistRequest, opts ...grpc.CallOption) (*ReorderWatchlistResponse, error) {
	out := new(ReorderWatchlistResponse)
	err := c.cc.Invoke(ctx, WatchlistService_ReorderWatchlist_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) CheckWatchlistItem(ctx context.Context, in *CheckWatchlistItemRequest, opts ...grpc.CallOption) (*CheckWatchlistItemResponse, error) {
	out := new(CheckWatchlistItemResponse)
	err := c.cc.Invoke(ctx, WatchlistService_CheckWatchlistItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchlistServiceServer is the server API for WatchlistService service.
// All implementations must embed UnimplementedWatchlistServiceServer
// for forward compatibility
type WatchlistServiceServer interface {
	CreateWatchlistItem(context.Context, *CreateWatchlistItemRequest) (*CreateWatchlistItemResponse, error)
	ListWatchlist(context.Context, *ListWatchlistRequest) (*ListWatchlistResponse, error)
	UpdateWatchlistItem(context.Context, *UpdateWatchlistItemRequest) (*UpdateWatchlistItemResponse, error)
	DeleteWatchlistItem(context.Context, *DeleteWatchlistItemRequest) (*DeleteWatchlistItemResponse, error)
	ReorderWatchlist(context.Context, *ReorderWatchlistRequest) (*ReorderWatchlistResponse, error)
	CheckWatchlistItem(context.Context, *CheckWatchlistItemRequest) (*CheckWatchlistItemResponse, error)
	mustEmbedUnimplementedWatchlistServiceServer()
}

// UnimplementedWatchlistServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWatchlistServiceServer struct {
}

func (UnimplementedWatchlistServiceServer) CreateWatchlistItem(context.Context, *CreateWatchlistItemRequest) (*CreateWatchlistItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWatchlistItem not implemented")
}
func (UnimplementedWatchlistServiceServer) ListWatchlist(context.Context, *ListWatchlistRequest) (*ListWatchlistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWatchlist not implemented")
}
func (UnimplementedWatchlistServiceServer) UpdateWatchlistItem(context.Context, *UpdateWatchlistItemRequest) (*UpdateWatchlistItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWatchlistItem not implemented")
}
func (UnimplementedWatchlistServiceServer) DeleteWatchlistItem(context.Context, *DeleteWatchlistItemRequest) (*DeleteWatchlistItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWatchlistItem not implemented")
}
func (UnimplementedWatchlistServiceServer) ReorderWatchlist(context.Context, *ReorderWatchlistRequest) (*ReorderWatchlistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderWatchlist not implemented")
}
func (UnimplementedWatchlistServiceServer) CheckWatchlistItem(context.Context, *CheckWatchlistItemRequest) (*CheckWatchlistItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckWatchlistItem not implemented")
}
func (UnimplementedWatchlistServiceServer) mustEmbedUnimplementedWatchlistServiceServer() {}

// UnsafeWatchlistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchlistServiceServer will
// result in compilation errors.
type UnsafeWatchlistServiceServer interface {
	mustEmbedUnimplementedWatchlistServiceServer()
}

func RegisterWatchlistServiceServer(s grpc.ServiceRegistrar, srv WatchlistServiceServer) {
	s.RegisterService(&WatchlistService_ServiceDesc, srv)
}

func _WatchlistService_CreateWatchlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWatchlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).CreateWatchlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_CreateWatchlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).CreateWatchlistItem(ctx, req.(*CreateWatchlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_ListWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).ListWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_ListWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).ListWatchlist(ctx, req.(*ListWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_UpdateWatchlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWatchlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).UpdateWatchlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_UpdateWatchlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).UpdateWatchlistItem(ctx, req.(*UpdateWatchlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_DeleteWatchlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWatchlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).DeleteWatchlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_DeleteWatchlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).DeleteWatchlistItem(ctx, req.(*DeleteWatchlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_ReorderWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).ReorderWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_ReorderWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).ReorderWatchlist(ctx, req.(*ReorderWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_CheckWatchlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckWatchlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).CheckWatchlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_CheckWatchlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).CheckWatchlistItem(ctx, req.(*CheckWatchlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatchlistService_ServiceDesc is the grpc.ServiceDesc for WatchlistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchlistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wealthjourney.watchlist.v1.WatchlistService",
	HandlerType: (*WatchlistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWatchlistItem",
			Handler:    _WatchlistService_CreateWatchlistItem_Handler,
		},
		{
			MethodName: "ListWatchlist",
			Handler:    _WatchlistService_ListWatchlist_Handler,
		},
		{
			MethodName: "UpdateWatchlistItem",
			Handler:    _WatchlistService_UpdateWatchlistItem_Handler,
		},
		{
			MethodName: "DeleteWatchlistItem",
			Handler:    _WatchlistService_DeleteWatchlistItem_Handler,
		},
		{
			MethodName: "ReorderWatchlist",
			Handler:    _WatchlistService_ReorderWatchlist_Handler,
		},
		{
			MethodName: "CheckWatchlistItem",
			Handler:    _WatchlistService_CheckWatchlistItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/v1/watchlist.proto",
}
