// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: protobuf/v1/gold_sentiment.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoldSentimentService_GetGoldSentiment_FullMethodName           = "/wealthjourney.v1.GoldSentimentService/GetGoldSentiment"
	GoldSentimentService_GetGoldSentimentComments_FullMethodName   = "/wealthjourney.v1.GoldSentimentService/GetGoldSentimentComments"
	GoldSentimentService_CastGoldVote_FullMethodName               = "/wealthjourney.v1.GoldSentimentService/CastGoldVote"
	GoldSentimentService_PostGoldSentimentComment_FullMethodName   = "/wealthjourney.v1.GoldSentimentService/PostGoldSentimentComment"
	GoldSentimentService_DeleteGoldSentimentComment_FullMethodName = "/wealthjourney.v1.GoldSentimentService/DeleteGoldSentimentComment"
)

// GoldSentimentServiceClient is the client API for GoldSentimentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoldSentimentServiceClient interface {
	GetGoldSentiment(ctx context.Context, in *GetGoldSentimentRequest, opts ...grpc.CallOption) (*GetGoldSentimentResponse, error)
	GetGoldSentimentComments(ctx context.Context, in *GetGoldSentimentCommentsRequest, opts ...grpc.CallOption) (*GetGoldSentimentCommentsResponse, error)
	// Public: Cast or update vote (auth optional, anonymous voting supported)
	CastGoldVote(ctx context.Context, in *CastGoldVoteRequest, opts ...grpc.CallOption) (*CastGoldVoteResponse, error)
	PostGoldSentimentComment(ctx context.Context, in *PostGoldSentimentCommentRequest, opts ...grpc.CallOption) (*PostGoldSentimentCommentResponse, error)
	DeleteGoldSentimentComment(ctx context.Context, in *DeleteGoldSentimentCommentRequest, opts ...grpc.CallOption) (*DeleteGoldSentimentCommentResponse, error)
}

type goldSentimentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoldSentimentServiceClient(cc grpc.ClientConnInterface) GoldSentimentServiceClient {
	return &goldSentimentServiceClient{cc}
}

func (c *goldSentimentServiceClient) GetGoldSentiment(ctx context.Context, in *GetGoldSentimentRequest, opts ...grpc.CallOption) (*GetGoldSentimentResponse, error) {
	out := new(GetGoldSentimentResponse)
	err := c.cc.Invoke(ctx, GoldSentimentService_GetGoldSentiment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldSentimentServiceClient) GetGoldSentimentComments(ctx context.Context, in *GetGoldSentimentCommentsRequest, opts ...grpc.CallOption) (*GetGoldSentimentCommentsResponse, error) {
	out := new(GetGoldSentimentCommentsResponse)
	err := c.cc.Invoke(ctx, GoldSentimentService_GetGoldSentimentComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldSentimentServiceClient) CastGoldVote(ctx context.Context, in *CastGoldVoteRequest, opts ...grpc.CallOption) (*CastGoldVoteResponse, error) {
	out := new(CastGoldVoteResponse)
	err := c.cc.Invoke(ctx, GoldSentimentService_CastGoldVote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldSentimentServiceClient) PostGoldSentimentComment(ctx context.Context, in *PostGoldSentimentCommentRequest, opts ...grpc.CallOption) (*PostGoldSentimentCommentResponse, error) {
	out := new(PostGoldSentimentCommentResponse)
	err := c.cc.Invoke(ctx, GoldSentimentService_PostGoldSentimentComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldSentimentServiceClient) DeleteGoldSentimentComment(ctx context.Context, in *DeleteGoldSentimentCommentRequest, opts ...grpc.CallOption) (*DeleteGoldSentimentCommentResponse, error) {
	out := new(DeleteGoldSentimentCommentResponse)
	err := c.cc.Invoke(ctx, GoldSentimentService_DeleteGoldSentimentComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoldSentimentServiceServer is the server API for GoldSentimentService service.
// All implementations must embed UnimplementedGoldSentimentServiceServer
// for forward compatibility
type GoldSentimentServiceServer interface {
	GetGoldSentiment(context.Context, *GetGoldSentimentRequest) (*GetGoldSentimentResponse, error)
	GetGoldSentimentComments(context.Context, *GetGoldSentimentCommentsRequest) (*GetGoldSentimentCommentsResponse, error)
	// Public: Cast or update vote (auth optional, anonymous voting supported)
	CastGoldVote(context.Context, *CastGoldVoteRequest) (*CastGoldVoteResponse, error)
	PostGoldSentimentComment(context.Context, *PostGoldSentimentCommentRequest) (*PostGoldSentimentCommentResponse, error)
	DeleteGoldSentimentComment(context.Context, *DeleteGoldSentimentCommentRequest) (*DeleteGoldSentimentCommentResponse, error)
	mustEmbedUnimplementedGoldSentimentServiceServer()
}

// UnimplementedGoldSentimentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoldSentimentServiceServer struct {
}

func (UnimplementedGoldSentimentServiceServer) GetGoldSentiment(context.Context, *GetGoldSentimentRequest) (*GetGoldSentimentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoldSentiment not implemented")
}
func (UnimplementedGoldSentimentServiceServer) GetGoldSentimentComments(context.Context, *GetGoldSentimentCommentsRequest) (*GetGoldSentimentCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoldSentimentComments not implemented")
}
func (UnimplementedGoldSentimentServiceServer) CastGoldVote(context.Context, *CastGoldVoteRequest) (*CastGoldVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastGoldVote not implemented")
}
func (UnimplementedGoldSentimentServiceServer) PostGoldSentimentComment(context.Context, *PostGoldSentimentCommentRequest) (*PostGoldSentimentCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostGoldSentimentComment not implemented")
}
func (UnimplementedGoldSentimentServiceServer) DeleteGoldSentimentComment(context.Context, *DeleteGoldSentimentCommentRequest) (*DeleteGoldSentimentCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGoldSentimentComment not implemented")
}
func (UnimplementedGoldSentimentServiceServer) mustEmbedUnimplementedGoldSentimentServiceServer() {}

// UnsafeGoldSentimentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoldSentimentServiceServer will
// result in compilation errors.
type UnsafeGoldSentimentServiceServer interface {
	mustEmbedUnimplementedGoldSentimentServiceServer()
}

func RegisterGoldSentimentServiceServer(s grpc.ServiceRegistrar, srv GoldSentimentServiceServer) {
	s.RegisterService(&GoldSentimentService_ServiceDesc, srv)
}

func _GoldSentimentService_GetGoldSentiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoldSentimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldSentimentServiceServer).GetGoldSentiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldSentimentService_GetGoldSentiment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldSentimentServiceServer).GetGoldSentiment(ctx, req.(*GetGoldSentimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoldSentimentService_GetGoldSentimentComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoldSentimentCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldSentimentServiceServer).GetGoldSentimentComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldSentimentService_GetGoldSentimentComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldSentimentServiceServer).GetGoldSentimentComments(ctx, req.(*GetGoldSentimentCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoldSentimentService_CastGoldVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastGoldVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldSentimentServiceServer).CastGoldVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldSentimentService_CastGoldVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldSentimentServiceServer).CastGoldVote(ctx, req.(*CastGoldVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoldSentimentService_PostGoldSentimentComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostGoldSentimentCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldSentimentServiceServer).PostGoldSentimentComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldSentimentService_PostGoldSentimentComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldSentimentServiceServer).PostGoldSentimentComment(ctx, req.(*PostGoldSentimentCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoldSentimentService_DeleteGoldSentimentComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGoldSentimentCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldSentimentServiceServer).DeleteGoldSentimentComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldSentimentService_DeleteGoldSentimentComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldSentimentServiceServer).DeleteGoldSentimentComment(ctx, req.(*DeleteGoldSentimentCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoldSentimentService_ServiceDesc is the grpc.ServiceDesc for GoldSentimentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoldSentimentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wealthjourney.v1.GoldSentimentService",
	HandlerType: (*GoldSentimentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoldSentiment",
			Handler:    _GoldSentimentService_GetGoldSentiment_Handler,
		},
		{
			MethodName: "GetGoldSentimentComments",
			Handler:    _GoldSentimentService_GetGoldSentimentComments_Handler,
		},
		{
			MethodName: "CastGoldVote",
			Handler:    _GoldSentimentService_CastGoldVote_Handler,
		},
		{
			MethodName: "PostGoldSentimentComment",
			Handler:    _GoldSentimentService_PostGoldSentimentComment_Handler,
		},
		{
			MethodName: "DeleteGoldSentimentComment",
			Handler:    _GoldSentimentService_DeleteGoldSentimentComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/v1/gold_sentiment.proto",
}
